name: tourism_app
description: "A tourism app."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6
  google_fonts: ^6.3.2
  speech_to_text: ^7.3.0
  google_maps_flutter: ^2.13.1
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  font_awesome_flutter: ^10.10.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  url_launcher: ^6.3.2
  flutter_tts: ^4.2.3
  shared_preferences: ^2.5.3
  http: ^1.5.0
  google_sign_in: ^7.2.0
  flutter_secure_storage: ^9.2.4
  image_picker: ^1.2.0
  markdown_widget: ^2.3.2+8
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/
    - assets/images/
    - assets/app/
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app/appicon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/app/appicon.png"
    background_color: "#ffffff"
    theme_color: "#0ba6da"
  windows:
    generate: true
    image_path: "assets/app/appicon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/app/appicon.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/app/splash.png
  android_12:
    color: "#FFFFFF"
    image: assets/app/splash.png
  web: false
